version: '3.7'
services:
  
  database:
    image: mysql
    env_file: database.conf
    volumes:
      - ./data:/var/lib/mysql

  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./blog:/blog
      - /tmp:/media
    depends_on:
      - database
    links:
      - "database:mysql_server"
  
  server:
    image: nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=example.ltd
      - NGINX_PROXY_SERVER=blog_app:5000
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PROXY_SERVER' < /etc/nginx/conf.d/blog.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
      - "app:blog_app"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/blog.template:ro
    depends_on:
      - app
